name: build & push

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      app:
        description: Name of app to build (must match a dir in apps/)
        required: false
        type: string
      version:
        description: Version of app to build
        required: false
        type: string

jobs:
  find-apps:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.apps.outputs.apps }}
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: list apps
        id: apps
        run: |
          if [ -z "${{ inputs.app }} ]; then
            echo "apps=$(ls ./apps | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}
          else
            echo "apps=${{ inputs.app }}" >> ${GITHUB_OUTPUT}
          fi

  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: find-apps
    strategy:
      matrix:
        app: ${{ fromJson(needs.find-apps.outputs.apps) }}
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: set version
        run: |
          if [ -z "${{ inputs.version }} ]; then
            echo "VERSION=${{ inputs.version }}" >> ${GITHUB_OUTPUT}
          else
            echo "VERSION=$(source ./apps/${{ matrix.app }}/latest.sh)" >> $GITHUB_ENV
          fi
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            VERSION
          context: ./apps/${{ matrix.app }}
          tags: |
            ghcr.io/luispflamminger/${{ matrix.app }}:${{ env.VERSION }}
            ghcr.io/luispflamminger/${{ matrix.app }}:latest

