name: build & push

on:
  schedule:
    - cron: '0 4 * * *'
  push:
  workflow_dispatch:

jobs:
  find-apps:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.apps.outputs.apps }}
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: list apps
        id: apps
        run: echo "apps=$(ls -d apps/*/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}

  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: find-apps
    strategy:
      matrix:
        app: ${{ fromJson(needs.find-apps.outputs.apps) }}
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: set version
        run: echo "VERSION=$(source ./apps/${{ matrix.app }}/latest.sh)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            VERSION
          context: ./apps/${{ matrix.app }}
          tags: |
            ghcr.io/luispflamminger/${{ matrix.app }}:${{ env.VERSION }}
            ghcr.io/luispflamminger/${{ matrix.app }}:latest

